In [ ]:
import pandas as pd
# df = pd.read_csv('archive/fifa_world_cup_2026_player_performance.csv')
# df["player_name"][0] = "Lionel Messi", Pandas does not allow direct assignment to a single cell in a DataFrame using the bracket notation.
# print(df)
# print(df.head())
# print(df.shape)
# print(df.describe())

# # How many unique nationalities?
# print(df['nationality'].nunique())

# # Which nationality has the most players?
# print(df['nationality'].value_counts().head(10))

# # Average age of all players
# print(df['age'].mean())

# # Filter only Spanish players
# spanish = df[df['nationality'] == 'Spanish']
# print(spanish.shape)

# # Top 5 players by tournament rating
# print(df.sort_values('tournament_rating', ascending=False).head())

# # Average tournament rating by nationality (top 10)
# print(df.groupby('nationality')['tournament_rating'].mean().sort_values(ascending=False).head(10))

# # Youngest and oldest player
# print(df['age'].min(), df['age'].max())

# # Players above average rating
# avg = df['tournament_rating'].mean()
# top = df[df['tournament_rating'] > avg]
# print(top.shape)

1. A one dimensional array capable of holding any data is series
2. A two dimensional array structured with columns of potentially diffrent types of data is DataFrame

In [ ]:
import pandas as pd
# s = pd.Series([1, 2, 3, 4, 5])
# print(s)

In [4]:
import pandas as pd
Dict1 = {"Name": ["Alice", "Bob", "Charlie", "David"],
         "Age": [25, 30, 35, 40],
         "City": ["New York", "Los Angeles", "Chicago", "Houston"]}

df = pd.DataFrame(Dict1)

df.index = ["1", "2", "3", "4"]
df.to_csv("dict1.csv", index=True)
print(pd.read_csv("dict1.csv", index_col=0))

      Name  Age         City
1    Alice   25     New York
2      Bob   30  Los Angeles
3  Charlie   35      Chicago
4    David   40      Houston

In [50]:
import numpy as np
import pandas as pd
newdf1 = pd.DataFrame(np.random.rand(544, 6), columns=['A', 'B', 'C', 'D', 'E', 'F'])

In [51]:
newdf1

            A         B         C         D         E         F
0    0.723310  0.238577  0.092521  0.310893  0.054083  0.105595
1    0.356824  0.303412  0.467406  0.071389  0.724697  0.608639
2    0.475116  0.150345  0.808592  0.818931  0.846196  0.254024
3    0.047417  0.121015  0.927940  0.361906  0.462638  0.141468
4    0.954239  0.911079  0.915326  0.741882  0.808790  0.029394
..        ...       ...       ...       ...       ...       ...
539  0.192752  0.568813  0.754749  0.024749  0.860067  0.653555
540  0.954799  0.416834  0.225480  0.341690  0.427959  0.175870
541  0.057097  0.924819  0.903408  0.789208  0.863906  0.018228
542  0.080231  0.057402  0.933972  0.995121  0.060105  0.421816
543  0.234414  0.010297  0.247003  0.607622  0.304460  0.589975

[544 rows x 6 columns]

In [ ]:
newdf1.head()

          A         B         C         D         E         F
0  0.712432  0.436713  0.740109  0.272215  0.317687  0.763808
1  0.654301  0.177346  0.051857  0.448779  0.411560  0.036265
2  0.073726  0.002136  0.016425  0.826524  0.545857  0.439208
3  0.409250  0.202243  0.915231  0.558066  0.536123  0.812027
4  0.172820  0.756439  0.611713  0.488513  0.906421  0.044771

In [ ]:
newdf1.loc[0:5, ['A', 'B']]

          A         B
0  0.712432  0.436713
1  0.654301  0.177346
2  0.073726  0.002136
3  0.409250  0.202243
4  0.172820  0.756439
5  0.122325  0.929446

In [ ]:
newdf1.loc[[4,5], :]

          A         B         C         D         E         F
4  0.172820  0.756439  0.611713  0.488513  0.906421  0.044771
5  0.122325  0.929446  0.710892  0.202657  0.644492  0.702381

In [ ]:
newdf1.loc[: ,["C", "D"]]

            C         D
0    0.740109  0.272215
1    0.051857  0.448779
2    0.016425  0.826524
3    0.915231  0.558066
4    0.611713  0.488513
..        ...       ...
539  0.148193  0.540101
540  0.004649  0.770863
541  0.676826  0.096199
542  0.857948  0.935453
543  0.914370  0.858813

[544 rows x 2 columns]

In [ ]:
newdf1.loc[(newdf1['A'] > 0.5) & (newdf1['B'] < 0.5)]

            A         B         C         D         E         F
0    0.712432  0.436713  0.740109  0.272215  0.317687  0.763808
1    0.654301  0.177346  0.051857  0.448779  0.411560  0.036265
10   0.845675  0.048389  0.914955  0.367583  0.574925  0.514869
13   0.590229  0.325458  0.243862  0.472667  0.128178  0.910727
14   0.872600  0.442081  0.485195  0.920538  0.075372  0.963246
..        ...       ...       ...       ...       ...       ...
539  0.957285  0.421044  0.148193  0.540101  0.098041  0.991297
540  0.852391  0.274201  0.004649  0.770863  0.741241  0.396878
541  0.633806  0.044847  0.676826  0.096199  0.483365  0.203262
542  0.707147  0.061199  0.857948  0.935453  0.869867  0.077593
543  0.787664  0.314646  0.914370  0.858813  0.333533  0.487102

[147 rows x 6 columns]

In [52]:
newdf1.iloc[0,5]

np.float64(0.10559523296716866)

In [53]:
newdf1.drop([0])

            A         B         C         D         E         F
1    0.356824  0.303412  0.467406  0.071389  0.724697  0.608639
2    0.475116  0.150345  0.808592  0.818931  0.846196  0.254024
3    0.047417  0.121015  0.927940  0.361906  0.462638  0.141468
4    0.954239  0.911079  0.915326  0.741882  0.808790  0.029394
5    0.977298  0.706769  0.515127  0.581171  0.220993  0.280960
..        ...       ...       ...       ...       ...       ...
539  0.192752  0.568813  0.754749  0.024749  0.860067  0.653555
540  0.954799  0.416834  0.225480  0.341690  0.427959  0.175870
541  0.057097  0.924819  0.903408  0.789208  0.863906  0.018228
542  0.080231  0.057402  0.933972  0.995121  0.060105  0.421816
543  0.234414  0.010297  0.247003  0.607622  0.304460  0.589975

[543 rows x 6 columns]

inplace = true modifies the original DataFrame

In [54]:
newdf1

            A         B         C         D         E         F
0    0.723310  0.238577  0.092521  0.310893  0.054083  0.105595
1    0.356824  0.303412  0.467406  0.071389  0.724697  0.608639
2    0.475116  0.150345  0.808592  0.818931  0.846196  0.254024
3    0.047417  0.121015  0.927940  0.361906  0.462638  0.141468
4    0.954239  0.911079  0.915326  0.741882  0.808790  0.029394
..        ...       ...       ...       ...       ...       ...
539  0.192752  0.568813  0.754749  0.024749  0.860067  0.653555
540  0.954799  0.416834  0.225480  0.341690  0.427959  0.175870
541  0.057097  0.924819  0.903408  0.789208  0.863906  0.018228
542  0.080231  0.057402  0.933972  0.995121  0.060105  0.421816
543  0.234414  0.010297  0.247003  0.607622  0.304460  0.589975

[544 rows x 6 columns]

In [55]:
newdf1.drop([1], inplace = True)

In [58]:
newdf1.shape

(543, 6)

In [60]:
newdf1.info()

<class 'pandas.DataFrame'>
Index: 543 entries, 0 to 543
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       543 non-null    float64
 1   B       543 non-null    float64
 2   C       543 non-null    float64
 3   D       543 non-null    float64
 4   E       543 non-null    float64
 5   F       543 non-null    float64
dtypes: float64(6)
memory usage: 29.7 KB

In [61]:
newdf1['A'].value_counts()

A
0.723310    1
0.475116    1
0.047417    1
0.954239    1
0.977298    1
           ..
0.192752    1
0.954799    1
0.057097    1
0.080231    1
0.234414    1
Name: count, Length: 543, dtype: int64

In [69]:
newdf1.describe()
newdf1.corr()
newdf1.mean()
newdf1.min()
# newdf1.max()
# newdf1.median()
# newdf1.std()
# newdf1.count()

A    0.000156
B    0.000102
C    0.004456
D    0.000206
E    0.005508
F    0.000718
dtype: float64